// 20210531115332
// https://api.github.com/users/devfritz

export default {
  "login": "Devfritz",
  "id": 50135831,
  "node_id": "MDQ6VXNlcjUwMTM1ODMx",
  "avatar_url": "https://avatars.githubusercontent.com/u/50135831?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Devfritz",
  "html_url": "https://github.com/Devfritz",
  "followers_url": "https://api.github.com/users/Devfritz/followers",
  "following_url": "https://api.github.com/users/Devfritz/following{/other_user}",
  "gists_url": "https://api.github.com/users/Devfritz/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Devfritz/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Devfritz/subscriptions",
  "organizations_url": "https://api.github.com/users/Devfritz/orgs",
  "repos_url": "https://api.github.com/users/Devfritz/repos",
  "events_url": "https://api.github.com/users/Devfritz/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Devfritz/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Fritz Gerlin Senat",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 12,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2019-04-30T08:47:31Z",
  "updated_at": "2021-05-11T14:13:43Z"
}